CREATE TABLE `ROLE` (
  `ROLE_ID` SMALLINT(6) NOT NULL,
  `ROLE_NAME` VARCHAR(50) NOT NULL,
  `ROLE_RIGHTS` ENUM('RO','RW') NOT NULL,
  PRIMARY KEY  (`ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `MENU_ITEM` (
  `MENU_ID` SMALLINT(6) NOT NULL,
  `MENU_TYPE` VARCHAR(10) NOT NULL, 
  `MENU_NAME` VARCHAR(50) NOT NULL,
  `MENU_URL` VARCHAR(50) NOT NULL,
  `MENU_IMG` VARCHAR(50) NOT NULL,
  `MENU_ORDER` SMALLINT(6) NOT NULL,
  `MENU_SHOW` SMALLINT(6) NOT NULL,
  PRIMARY KEY  (`MENU_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `ROLE_PROFILE` (
  `RP_ID` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` SMALLINT(6) NOT NULL,
  `RES_ID` SMALLINT(6) NOT NULL,
  CONSTRAINT `FK_ROLE_PROFILE_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`),
  CONSTRAINT `FK_ROLE_PROFILE_2` FOREIGN KEY (`RES_ID`) REFERENCES `MENU_ITEM`(`MENU_ID`),
  PRIMARY KEY  (`RP_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `COUNTRY` (
  `COUNTRY_ID` SMALLINT(6) NOT NULL,
  `COUNTRY_CODE` VARCHAR(10) NOT NULL,
  `COUNTRY_NAME` VARCHAR(50) NOT NULL,
  `ISO_CODE` VARCHAR(10) NULL,
  PRIMARY KEY  (`COUNTRY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `WILEY_OFFICES` (
  `OFFICE_ID` SMALLINT(6) NOT NULL,
  `OFFICE_NAME` VARCHAR(50) NOT NULL,
  `TIME_DIFF_TO_EST` DECIMAL(3,1) NOT NULL,  -- Changes Made in datatype from smallint to decimal
  PRIMARY KEY  (`OFFICE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `USER` (
  `USR_ID` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(100)  NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `PHONE_NO` VARCHAR(50) NOT NULL,
  `MOBILE_NO` VARCHAR(50) DEFAULT NULL,
  `IS_ACTIVE` SMALLINT(1) DEFAULT '1' NOT NULL,	--	0 - InActive, 1 - Active
  `IS_KEY_CONTACT` SMALLINT(1) DEFAULT '0' NOT NULL,	--	0 - NO, 1 - YES
  `COUNTRY_ID` SMALLINT(6) NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_DATE` DATETIME NOT NULL,
  `ROLE_ID` SMALLINT(6) NOT NULL,
  PRIMARY KEY  (`USR_ID`),
  UNIQUE KEY  (`USER_NAME`),
  CONSTRAINT `FK_USER_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`),
  CONSTRAINT `FK_USER_2` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `WILEY_OFFICES` (`OFFICE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

-- Created By & Updated By needs to be changed to smallint (6) from varchar(50) & would capture the usr_id of user creating or updating record
-- Additional record in user tabel to be inserted for SYSTEM user (automated application events). 
-- SYSTEM user would not be searchable or modifiable in user accounts interface
-- This change to be made in all tables wherever applicable
-- No foreign key check for these fields at time of insertion or updation of record.

CREATE TABLE `CUSTOMER` (
  `CUST_ID` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` VARCHAR(50) NOT NULL,
  `PHONE_NO` VARCHAR(50) DEFAULT NULL,
  `ADDRESS` VARCHAR(255) DEFAULT NULL,
  `ADD_CITY` VARCHAR(50) DEFAULT NULL,
  `ADD_STATE` VARCHAR(50) DEFAULT NULL,
  `ADD_ZIPCODE` VARCHAR(10) DEFAULT NULL,
  `COUNTRY_ID` SMALLINT(6) NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_DATE` DATETIME NOT NULL,
  PRIMARY KEY  (`CUST_ID`),
  UNIQUE KEY  (`COMPANY_NAME`),
  CONSTRAINT `FK_CUSTOMER_1` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`COUNTRY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `KEY_CONTACT` (
  `KC_ID` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `CUST_ID` SMALLINT(6) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `PHONE_NO` VARCHAR(50) NOT NULL,
  `MOBILE_NO` VARCHAR(50) DEFAULT NULL,
  `ADDRESS` VARCHAR(255) DEFAULT NULL,
  `ADD_CITY` VARCHAR(50) DEFAULT NULL,
  `ADD_STATE` VARCHAR(50) DEFAULT NULL,
  `ADD_ZIPCODE` VARCHAR(10) DEFAULT NULL,
  `COUNTRY_ID` SMALLINT(6) NOT NULL,
  `IS_ACTIVE` SMALLINT(1) DEFAULT '1' NOT NULL,	--	0 - InActive, 1 - Active
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_DATE` DATETIME NOT NULL,
  PRIMARY KEY  (`KC_ID`),
  CONSTRAINT `FK_KEY_CONTACT_1` FOREIGN KEY (`CUST_ID`) REFERENCES `CUSTOMER` (`CUST_ID`),
  CONSTRAINT `FK_KEY_CONTACT_2` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`COUNTRY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

  CREATE TABLE `PROJECT_SEQUENCE` (
  `PROJECT_ID` INT(10) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

  CREATE TABLE `PROJECT` (
  `PROJECT_ID` INT(10) NOT NULL,
  `PROJECT_NAME` VARCHAR(20) NOT NULL,
  `PRJ_ADMIN` SMALLINT(6) NOT NULL,
  `REQUESTER` SMALLINT(6) NOT NULL,
  `CUSTOMER` SMALLINT(6) NOT NULL,
  `PROJECT_STATUS` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - Pending	2 - Active 3 - InActive 4 - Deleted
  `NOTES` VARCHAR(2000) NULL,
  `PROJECT_TYPE` SMALLINT(1) DEFAULT '2' NOT NULL,		--	1 - Single	2 - Multiple
  `ST_URL` VARCHAR(255) NULL,
  `ECOMP` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO
  `AVAILABLE_DATE` DATETIME NULL,
  `EXPIRY_DATE` DATETIME NULL,
  `THRESOLD_DATE` DATETIME NULL,
  `DRM` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO
  `REGISTRATION` SMALLINT(1) DEFAULT '0' NOT NULL,		--	0 - NO	1 - Mandatory 2 - Optional [1,2 = Yes]
  `PROMO_CODE` SMALLINT(1) DEFAULT '0' NOT NULL,		--	0 - NO	1 - Mandatory 2 - Optional [1,2 = Yes]
  `SOLD_QTY` SMALLINT(6) NULL,
  `BACKUP_QTY` SMALLINT(6) NULL,
  `THRESOLD_QTY` SMALLINT(6) NULL,
--  `DOWNLOADED_COUNT` SMALLINT(6) NULL,  Field to be removed as downloaded count would be kept at file level.
  `PRINT_ALLOWED` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO
  `COPY_ALLOWED` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO
  `CONVERSION_ALLOWED` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO
  `PROJECT_TEMPLATE` VARCHAR(50) NULL,
  `CREATED_BY` SMALLINT(6) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `UPDATED_BY` SMALLINT(6) NOT NULL,
  `UPDATED_DATE` DATETIME NOT NULL,
  `URL_FLAG` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO (1 WHEN SOLD_QTY>0, ST_URL NOT NULL, URL & PROMOCODE GENERATED AFTER PROJECT CHANGES)
  `CONTENT_FLAG` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO (1 WHEN ALL CONTENT FILES FOR PROJECT ARE IN EFULFILLMENT CONTENT STORE)
  `TEMPLATE_FLAG` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO (1 WHEN WEBSITE PAGE HAS BEEN SAVED & COPIED TO DOWNLOAD WEB FOLDER)
  `ONCE_ACTIVE` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO (GETS RESET TO 0 IF INACTIVE PROJECT IS TAKEN TO PENDING STATE)
  PRIMARY KEY  (`PROJECT_ID`),
  UNIQUE KEY  (`PROJECT_NAME`),
  CONSTRAINT `FK_PROJECT_1` FOREIGN KEY (`PRJ_ADMIN`) REFERENCES `USER` (`USR_ID`),
  CONSTRAINT `FK_PROJECT_2` FOREIGN KEY (`REQUESTER`) REFERENCES `USER` (`USR_ID`),
  CONSTRAINT `FK_PROJECT_3` FOREIGN KEY (`CUSTOMER`) REFERENCES `CUSTOMER` (`CUST_ID`),
  CONSTRAINT `FK_PROJECT_4` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USR_ID`),
  CONSTRAINT `FK_PROJECT_5` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USR_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

  CREATE TABLE `PROJECT_MOMENTUM` (
  `PRJ_MOMENTUM_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NOT NULL,
  `PROJECT_NAME` VARCHAR(20) NOT NULL,
  `PRJ_ADMIN` SMALLINT(6) NOT NULL,
  `REQUESTER` SMALLINT(6) NOT NULL,
  `CUSTOMER` SMALLINT(6) NOT NULL,
  `PROJECT_STATUS` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - Pending	2 - Active 3 - InActive 4 - Deleted
  `NOTES` VARCHAR(2000) NULL,
  `PROJECT_TYPE` SMALLINT(1) DEFAULT '2' NOT NULL,		--	1 - Single	2 - Multiple
  `ST_URL` VARCHAR(255) NULL,
  `ECOMP` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO
  `AVAILABLE_DATE` DATETIME NULL,
  `EXPIRY_DATE` DATETIME NULL,
  `THRESOLD_DATE` DATETIME NULL,
  `DRM` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO
  `REGISTRATION` SMALLINT(1) DEFAULT '0' NOT NULL,		--	0 - NO	1 - Mandatory 2 - Optional [1,2 = Yes]
  `PROMO_CODE` SMALLINT(1) DEFAULT '0' NOT NULL,		--	0 - NO	1 - Mandatory 2 - Optional [1,2 = Yes]
  `SOLD_QTY` SMALLINT(6) NULL,
  `BACKUP_QTY` SMALLINT(6) NULL,
  `THRESOLD_QTY` SMALLINT(6) NULL,
--  `DOWNLOADED_COUNT` SMALLINT(6) NULL,    This field is being moved to file level.
  `PRINT_ALLOWED` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO
  `COPY_ALLOWED` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO
  `CONVERSION_ALLOWED` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO
  `PROJECT_TEMPLATE` VARCHAR(50) NULL,
  `CREATED_BY` SMALLINT(6) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `UPDATED_BY` SMALLINT(6) NOT NULL,
  `UPDATED_DATE` DATETIME NOT NULL,
  `URL_FLAG` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO
  `CONTENT_FLAG` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO
  `TEMPLATE_FLAG` SMALLINT(1) DEFAULT '0' NOT NULL,		--	1 - YES	0 - NO
  `ONCE_ACTIVE` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	0 - NO (ONCE_ACTIVE IS DEFAULT 1 HERE)
  PRIMARY KEY  (`PRJ_MOMENTUM_ID`),
  CONSTRAINT `FK_PROJECT_MOMENTUM_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_PROJECT_MOMENTUM_2` FOREIGN KEY (`PRJ_ADMIN`) REFERENCES `USER` (`USR_ID`),
  CONSTRAINT `FK_PROJECT_MOMENTUM_3` FOREIGN KEY (`REQUESTER`) REFERENCES `USER` (`USR_ID`),
  CONSTRAINT `FK_PROJECT_MOMENTUM_4` FOREIGN KEY (`CUSTOMER`) REFERENCES `CUSTOMER` (`CUST_ID`),
  CONSTRAINT `FK_PROJECT_MOMENTUM_5` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USR_ID`),
  CONSTRAINT `FK_PROJECT_MOMENTUM_6` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USR_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `DYNAMIC_FIELDS` (
  `FLD_ID` SMALLINT(6) NOT NULL,
  `FLD_NAME` VARCHAR(100) NOT NULL,
  `FLD_TYPE` ENUM('TEXT','BIGTEXT','DROPDOWN','RADIO') NOT NULL,
  PRIMARY KEY  (`FLD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONTENT_FILES` (
  `CF_ID` INT(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `FILE_ID` VARCHAR(20) NOT NULL,
  `FILE_NAME` VARCHAR(100) NULL,
  `FILE_TYPE` SMALLINT(1) DEFAULT '1' NOT NULL,		-- New Field	1 - Cover	2 - Content 
  `FILE_SIZE` INT(10) NULL,
  `TITLE` VARCHAR(100) NULL,
  `AUTHORS` VARCHAR(100) NULL,
  `NO_OF_PAGES` SMALLINT(6) NULL,
  `PUBLICATION_DATE` DATETIME NULL,
  `FILE_STATUS` SMALLINT(1) DEFAULT '0' NOT NULL,		--	0 - None	1 - Uploaded	2 - Activated	3 - Archived
  `DOWNLOAD_URL` VARCHAR(255) NULL,     -- NEW FIELD DOWNLOAD URL FOR FILE AS SUPPLIED BY EFULFILLMENT SERVICE
  `DOWNLOAD_COUNT` SMALLINT(6) DEFAULT '0' NOT NULL, -- NEW FIELD STORES COUNT OF THE TIMES FILE HAS BEEN SUCCESFULLY DOWNLOADED. INITIAL VALUE AT CREATION IS "0"
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_DATE` DATETIME NOT NULL,
  PRIMARY KEY  (`CF_ID`),
  CONSTRAINT `FK_CONTENT_FILES_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_CONTENT_FILES_2` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PROJECT_HISTORY` (
  `HST_ID` INT(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `FIELD_NAME` VARCHAR(20) NULL,
  `PREV_VALUE` VARCHAR(20) NULL,
  `CURR_VALUE` VARCHAR(20) NULL,
  `NOTIFICATION` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - YES	2 - NO
  `CREATED_BY` SMALLINT(6) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  PRIMARY KEY  (`HST_ID`),
  CONSTRAINT `FK_PROJECT_HISTORY_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_PROJECT_HISTORY_2` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`),
  CONSTRAINT `FK_PROJECT_HISTORY_3` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `REGISTRATION_DETAILS` (
  `RECORD_ID` INT(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `IP_ADDRESS` VARCHAR(20) NULL,
  `URL_USED` VARCHAR(200) NOT NULL, 		-- NEW FIELD STORES URL USED FROM WHICH REGISTRATION IS DONE
  `REGISTRATION_OBJECT` BLOB NOT NULL,
  PRIMARY KEY  (`RECORD_ID`),
  CONSTRAINT `FK_REGISTRATION_DETAILS_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_REGISTRATION_DETAILS_2` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TRANSACTION_LOG` (
  `LOG_ID` INT(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `CF_ID` INT(20) NULL,		-- NEW FIELD TO BE USED IN CASE DOWNLOAD IS A SUCCESS OR DOWNLOAD FAILED
  `RECORD_ID` INT(20) NULL,		-- NEW FIELD
  `TOKEN_ID` VARCHAR(20) NOT NULL,		-- New FIELD
  `IP_ADDRESS` VARCHAR(20) NOT NULL,
  `URL` VARCHAR(255) NOT NULL,
  `DOWNLOAD_URL` VARCHAR(255) NULL,
  `PROMO_CODE` VARCHAR(15) NULL,
  `REGISTRATION_NAME` VARCHAR(20) NULL,		-- New FIELD
  `ACTIVITY_DATE` DATETIME NOT NULL,
  `ACTIVITY_TYPE` ENUM('SUCCESS','FAIL','BROWSE') NOT NULL,	-- Aborted = Browse
  PRIMARY KEY  (`LOG_ID`),
  CONSTRAINT `FK_TRANSACTION_LOG_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_TRANSACTION_LOG_2` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- This table is not in use.
CREATE TABLE `WORKFLOW_EXCEPTION` (
  `EVENT_ID` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `EVENT_DESC` VARCHAR(200) NOT NULL,
  `TEMPLATE_PATH` VARCHAR(200) NOT NULL,
  PRIMARY KEY  (`EVENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PROMO_CODE_CONFIG` (
  `PCODE_CONF_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `STYLE` ENUM('MANUAL','PREFIX','AUTO') NOT NULL,
  `CODE_TYPE` ENUM('SINGLE','MULTI') NULL,
  `CODE_SIZE` ENUM('5-ALPHANUMERIC','6-ALPHANUMERIC','7-ALPHANUMERIC','8-ALPHANUMERIC') NULL,
  `QTY` SMALLINT(6) NULL,
  `CODE_PREFIX` VARCHAR(10) NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_DATE` DATETIME NOT NULL,
  PRIMARY KEY  (`PCODE_CONF_ID`),
  CONSTRAINT `FK_PROMO_CODE_CONFIG_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_PROMO_CODE_CONFIG_2` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PROMO_CODE_VALUES` (
  `AUTO_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `PROMO_CODE` VARCHAR(15) NOT NULL,
  `CODE_TYPE` ENUM('SINGLE','MULTI') NULL,
  `CODE_STATUS` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - Used	2 - Unused
  `IP_ADDRESS` VARCHAR(20) NULL,	-- NEW FIELD, IP ADDRESS FROM WHICH PROMO CODE USED
  `URL_USED` VARCHAR(200) NULL, 	-- NEW FIELD, URL FROM WHICH PROMO CODE USED
  `GENERATED_BY` VARCHAR(50)  NOT NULL,
  `GENERATED_DATE` DATETIME NOT NULL,
  `COUNT` INT(10) DEFAULT NULL,
  PRIMARY KEY  (`AUTO_ID`),
  UNIQUE KEY  (`PROJECT_ID`,`PRJ_MOMENTUM_ID`,`PROMO_CODE`),
  CONSTRAINT `FK_PROMO_CODE_VALUES_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_PROMO_CODE_VALUES_2` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PROJECT_URL` (
  `AUTO_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `URL` VARCHAR(255) NOT NULL,
  `URL_TYPE` ENUM('SINGLE','MULTI') NULL,
  `CODE_STATUS` SMALLINT(1) DEFAULT '1' NOT NULL,		--	1 - Used	2 - Unused
  `GENERATED_BY` VARCHAR(50)  NOT NULL,
  `GENERATED_DATE` DATETIME NOT NULL,
  `URL_COUNT` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY  (`AUTO_ID`),
  UNIQUE KEY  (`PROJECT_ID`,`PRJ_MOMENTUM_ID`,`URL`),
  CONSTRAINT `FK_PROJECT_URL_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_PROJECT_URL_2` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `WEBSITE_TEMPLATE` (
  `TEMPLATE_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(10) NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `NAME` VARCHAR(50) NOT NULL,
  `TYPE` ENUM('SYSTEM','USER') NOT NULL,
  `CATEGORY` ENUM('SINGLE','MULTI','BLANK') NOT NULL,
  `TITLE` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(250) NOT NULL,
  `PAGE_COUNT` SMALLINT(1) NOT NULL DEFAULT '2' NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_DATE` DATETIME NOT NULL,
  PRIMARY KEY  (`TEMPLATE_ID`),
  UNIQUE KEY  (`PROJECT_ID`,`PRJ_MOMENTUM_ID`),
  UNIQUE KEY  (`NAME`),
  CONSTRAINT `FK_WEBSITE_TEMPLATE_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_WEBSITE_TEMPLATE_2` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PROJECT_FIELDS` (
  `AUTO_ID` INT(10)  NOT NULL AUTO_INCREMENT,
  `TEMPLATE_ID` INT(10) NOT NULL,
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `FLD_ID` SMALLINT(6) NOT NULL,
  `FLD_TEXT` VARCHAR(100) NOT NULL, -- ANALOGOUS TO FLD_NAME IN DYNAMIC FIELDS TABLE
  `FLD_MANDATORY` SMALLINT(1) NOT NULL,	-- 1 - YES	0 - NO
  `FLD_ORDER` SMALLINT(6) NOT NULL,
  `FLD_DEFAULT` VARCHAR(100) NULL, -- NEW FIELD TO BE INCLUDED IF NOT KEPT IN WEBSITE PAGE FOR PROJECT
  `FLD_FOOTNOTE` VARCHAR(100) NULL, -- NEW FIELD TO BE INCLUDED IF NOT KEPT IN WEBSITE PAGE FOR PROJECT
  PRIMARY KEY  (`AUTO_ID`),
  CONSTRAINT `FK_PROJECT_FIELDS_1` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `WEBSITE_TEMPLATE` (`TEMPLATE_ID`),
  CONSTRAINT `FK_PROJECT_FIELDS_2` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_PROJECT_FIELDS_3` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`),
  CONSTRAINT `FK_PROJECT_FIELDS_4` FOREIGN KEY (`FLD_ID`) REFERENCES `DYNAMIC_FIELDS` (`FLD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `WEBSITE_EXCEPTION_MESSAGE` (
  `MSG_ID` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `EXCEPTION_EVENT` VARCHAR(255) NOT NULL,
  `EXCEPTION_TEXT` VARCHAR(255) NOT NULL,
  PRIMARY KEY  (`MSG_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PROJECT_EXCEPTION_MESSAGE` (
  `AUTO_ID` INT(10) NOT NULL AUTO_INCREMENT, 
  `MSG_ID` SMALLINT(6) NOT NULL, 
  `PROJECT_ID` INT(10) NOT NULL,
  `PRJ_MOMENTUM_ID` INT(10) NULL,	--	New Field
  `EXCEPTION_EVENT` VARCHAR(255) NOT NULL,
  `EXCEPTION_TEXT` VARCHAR(255) NOT NULL,
  PRIMARY KEY  (`AUTO_ID`),
  CONSTRAINT `FK_PROJECT_EXCEPTION_MESSAGE_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `FK_PROJECT_EXCEPTION_MESSAGE_2` FOREIGN KEY (`MSG_ID`) REFERENCES `WEBSITE_EXCEPTION_MESSAGE` (`MSG_ID`),
  CONSTRAINT `FK_PROJECT_EXCEPTION_MESSAGE_3` FOREIGN KEY (`PRJ_MOMENTUM_ID`) REFERENCES `PROJECT_MOMENTUM` (`PRJ_MOMENTUM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;



There are 11 notifications which system needs to generate. 6 of these are being logged in project history table & notification emails are being sent for these. There are 5 others & more could be added in future for which notification emails will need to be sent without logging.(nos 5,6,7,8,10 in FSD). We will need a mehanism to implement this.

Message queue table may need to be created instead of directly sending emails through the serveras at present.

It needs to be confirmed whether all forming part of Default Master in FSd are in properties file.





